### ISSUE TITLE
啥玩意這是

### ISSUE THREAD

**Issue by fissssssh** [seymourtang/concurrency-map#2]

**Comment by seymourtang** [comment]
A thread safe map based on segmented lock implementation.

**Comment by fissssssh** [comment]
> A thread safe map based on segmented lock implementation.

为什么一个并发map里面要放很多个小map

**Comment by seymourtang** [comment]
> > A thread safe map based on segmented lock implementation.
> 
> 为什么一个并发map里面要放很多个小map

Implement segmented locks to reduce lock strength.
